name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the wrt54g repository! Thanks for opening your first issue in the wrt54g repo!'
        pr-message: 'Welcome to the wrt54g repository! Thanks for opening your first pull request in the wrt54g repo!'
